---
- name: Install NFS server on CP
  gather_facts: true
  become: true
  hosts: gce_group_cp[0]
  tasks:
    - name: Install NFS server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: true

    - name: Create NFS dir
      ansible.builtin.file:
        path: "{{ nfs_path }}"
        state: directory
        recurse: true
        owner: root
        group: root
        mode: '1777'

    - name: Add NFS export
      ansible.builtin.copy:
        content: "{{ nfs_path }}/ *(rw,sync,no_root_squash,subtree_check)"
        dest: /etc/exports
        owner: root
        group: root
        mode: '0640'

    - name: Update exports
      ansible.builtin.command:
        cmd: exportfs -ra
      register: result
      changed_when: result.rc == 0
