---
- name: Start IAP tunnel for kubectl
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Establish TCP tunnel for load balancer stats
      ansible.builtin.shell:
        cmd: |
          nohup gcloud compute start-iap-tunnel \
          {{ groups.gce_group_lb[0] }} 9999 \
          --local-host-port=localhost:9999 \
          --zone={{ zone }} > /dev/null 2>&1 &

    - name: Establish TCP tunnel for load balancer kubernetes port
      ansible.builtin.shell:
        cmd: |
          nohup gcloud compute start-iap-tunnel \
          {{ groups.gce_group_lb[0] }} 6443 \
          --local-host-port=localhost:6443 \
          --zone={{ zone }} > /dev/null 2>&1 &

    - name: Add load balancer hostname to hosts file
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        insertafter: EOF
        line: '127.0.0.1 {{ groups.gce_group_lb[0] }}'
        state: present
      become: true

    - name: Wait for 1min
      ansible.builtin.wait_for:
        timeout: 60

    - name: Run kubernetes preparation script
      ansible.builtin.shell:
        cmd: ../scripts/prepare-kubernetes.sh
      register: output
      changed_when: output.rc != 0

    - name: Preparation script output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines + output.stderr_lines }}"

    - name: End message
      ansible.builtin.debug:
        msg: "Load balancer stats URL: http://localhost:9999/stats"
