---
- name: Include a play for common tasks
  ansible.builtin.import_playbook: playbooks/common.yml

- name: Include a play for controller-plane tasks
  ansible.builtin.import_playbook: playbooks/controller-plane.yml