---
- name: Include a play for common tasks
  ansible.builtin.import_playbook: playbooks/common.yml

- name: Include a play for controller-plane tasks
  ansible.builtin.import_playbook: playbooks/controller-plane.yml

- name: Include a play for joining nodes to k8s
  ansible.builtin.import_playbook: playbooks/join-workers.yml

- name: Include a play for NFS server
  ansible.builtin.import_playbook: playbooks/nfs-server.yml

- name: Include a play for starting IAP tunnel
  ansible.builtin.import_playbook: playbooks/start-iap-tunnel.yml
